### ISSUE TITLE
[Eternal Darkness] Failed To Create Workspace

### ISSUE THREAD

**Issue by MorseAmalgam** [NicholasMoser/GNTool#167]
Trying to get to the Audio Utilities, but since it requires a full workspace to work with the files, I've been trying to get the ISO to extract. The Audio files are successfully extracted (as .POO/.PRO/.SAM/.SDI) but the workspace fails to be created completely.
```
Oct 24, 2024 1:11:43 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Exporting files...
Oct 24, 2024 1:12:07 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Finished exporting files.
Oct 24, 2024 1:12:07 PM com.github.nicholasmoser.gnt4.GNT4Extractor unpackFPKs
INFO: Copying F:\Eternal Darkness\compressed to F:\Eternal Darkness\uncompressed
Oct 24, 2024 1:12:30 PM com.github.nicholasmoser.FPKUnpacker unpackDirectory
INFO: Unpacking FPKs...
Oct 24, 2024 1:12:30 PM com.github.nicholasmoser.GNTool$1 call
SEVERE: Error Extracting ISO
java.nio.file.NoSuchFileException: F:\Eternal Darkness\uncompressed\files\fpack
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at com.github.nicholasmoser.merged.module@4.5.1-SNAPSHOT/com.google.common.io.MoreFiles.deleteRecursivelyInsecure(Unknown Source)
	at com.github.nicholasmoser.merged.module@4.5.1-SNAPSHOT/com.google.common.io.MoreFiles.deleteRecursively(Unknown Source)
	at com.github.nicholasmoser@4.5.1-SNAPSHOT/com.github.nicholasmoser.FPKUnpacker.unpackDirectory(Unknown Source)
	at com.github.nicholasmoser@4.5.1-SNAPSHOT/com.github.nicholasmoser.gnt4.GNT4Extractor.unpackFPKs(Unknown Source)
	at com.github.nicholasmoser@4.5.1-SNAPSHOT/com.github.nicholasmoser.GNTool$1.call(Unknown Source)
	at com.github.nicholasmoser@4.5.1-SNAPSHOT/com.github.nicholasmoser.GNTool$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
There's no fpack folder in the compressed version, but there's no other information so I'm unsure if that's because of an issue extracting data from the ISO, or if the ISO doesn't contain an fpack directory for it to extract.

**Comment by NicholasMoser** [comment]
Only one game currently supports creating a workspace, but I could make the audio tools available from the Tools menu if you need it.

**Comment by MorseAmalgam** [comment]
That's fine - I was looking for SAM/SDI support and tunnel visioned when the audio.md readme search result came up, not realizing this was for a specific game. I think I can get it working via the MusyX extractor you're using, I just didn't read through the details and assumed GN was a shorter version of GCN. This project is the first one that even seems to know what SAM/SDI files are, and ended up being the only lead pointing me to Musyx Extract.

**Comment by NicholasMoser** [comment]
Sounds good. Let me know if you need my tools to do anything more, as long as there's overlap with the current functionality.
